# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  pokemonsapiweb:
    image: pokemonsapiweb
    build:
      context: .
      dockerfile: PokemonsAPI/PokemonsAPI.WEB/Dockerfile
    environment:
      - DB_CONNECTION_STRING=Server=localhost,1444;User=sa;Password=Passw0rd;database=PokeApi;trustServerCertificate=true;
    ports:
      - 5121:5121
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: Passw0rd
      ACCEPT_EULA: Y
    ports:
      - 1444:1433
  pokemonapp:
    image: pokemonapp
    build:
      context: ./pokemon-app
      dockerfile: Dockerfile
    ports:
      - 3005:3000